name: "Foe Be Gone"
description: "AI-powered wildlife detection and deterrent system"
version: "1.0.1"
slug: "foe-be-gone"
init: false
arch:
  - aarch64
  - amd64
startup: application
boot: auto
options:
  openai_api_key: ""
  openai_model: "gpt-4o-mini"
  capture_all_snapshots: false
  phash_threshold: 15
schema:
  openai_api_key: "str"
  openai_model: "list(gpt-4o-mini|gpt-4o|gpt-4-turbo)"
  capture_all_snapshots: "bool"
  phash_threshold: "int(1,30)"
ports:
  8000/tcp: 8000
ingress: true
ingress_port: 8000
panel_icon: mdi:bird
panel_title: "Foe Be Gone"
map:
  - share:rw
  - ssl
  - config:rw
  - media:rw
environment:
  DATA_PATH: "/data"
  SNAPSHOT_PATH: "/share/foe-be-gone/snapshots"
  VIDEO_PATH: "/share/foe-be-gone/videos"
  SOUND_PATH: "/share/foe-be-gone/sounds"
  DATABASE_URL: "sqlite:///data/foe_be_gone.db"
image: "ghcr.io/mneuhaus/{arch}-addon-foe-be-gone"