version: '3.8'

services:
  foe-be-gone:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DETECTION_INTERVAL=10
      - MIN_FOE_CONFIDENCE=0.7
      - ENABLE_DETERRENT=true
      - DETERRENT_DURATION=10
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/data
      - ./public/sounds:/data/sounds:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s