version: '3.8'

services:
  foe-be-gone:
    build:
      context: .
      args:
        BUILD_FROM: ghcr.io/home-assistant/amd64-base:3.21
    ports:
      - "8000:8000"
    volumes:
      - ./test-data:/data
      - ./test-share:/share
    environment:
      - CAPTURE_ALL_SNAPSHOTS=false
      - PHASH_THRESHOLD=15
      - DATABASE_URL=sqlite:////data/foe_be_gone.db
    command: ["/opt/foe-be-gone/scripts/run-test.sh"]