build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
  armhf: "ghcr.io/home-assistant/armhf-base:3.21"
  armv7: "ghcr.io/home-assistant/armv7-base:3.21"
  i386: "ghcr.io/home-assistant/i386-base:3.21"
codenotary:
  signer: "ghcr.io/mneuhaus/foe-be-gone"
labels:
  org.opencontainers.image.title: "Foe Be Gone"
  org.opencontainers.image.description: "AI-powered wildlife detection and deterrent system"
  org.opencontainers.image.source: "https://github.com/mneuhaus/foe-be-gone"
  org.opencontainers.image.url: "https://github.com/mneuhaus/foe-be-gone"
  org.opencontainers.image.documentation: "https://github.com/mneuhaus/foe-be-gone/blob/main/README.md"
  org.opencontainers.image.licenses: "MIT"
  io.hass.type: "addon"
  io.hass.arch: "aarch64|amd64|armhf|armv7|i386"