name: "Foe Be Gone"
version: "2.0.0"
slug: "foe_be_gone"
description: "AI-powered wildlife detection and deterrent system"
url: "https://github.com/mneuhaus/foe-be-gone"
image: "ghcr.io/mneuhaus/{arch}-addon-foe-be-gone"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
ingress: true
ingress_port: 8000
panel_icon: mdi:bird
homeassistant_api: true
audio: true
hassio_api: true
host_network: false
auth_api: false
map:
  - media:rw
  - config:rw
options: {}
schema: {}
environment:
  PYTHONUNBUFFERED: "1"
ports:
  8000/tcp: null
ports_description:
  8000/tcp: "Web interface (when not using ingress)"