"""Remove last_image_hash column from devices table

Revision ID: f8e9d7c6b5a4
Revises: ae4702f5cd12
Create Date: 2025-06-02 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e9d7c6b5a4'
down_revision: Union[str, None] = 'ae4702f5cd12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Remove last_image_hash column from devices table."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('last_image_hash')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Re-add last_image_hash column to devices table."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_image_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###